layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
#include "Structures.glsl"

#pragma USE_RESOURCES VolumetricForward

void main() {
    int idx = int(gl_GlobalInvocationID.x);
    if (imageLoad(ClusterFlags, idx).r != 0) {
        uint unique_idx = imageAtomicAdd(UniqueClustersCounter, int(0), int(1));
        imageStore(UniqueClusters, int(unique_idx), uvec4(idx, 0, 0, 0));
    }
}
